version: "2"
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=api
      - MYSQL_ROOT_PASSWORD=password
    expose:
      - 3306
  users:
    build:
      context: ./users
    command: ["sbt","run"]
    volumes:
      - "./commons:/app/commons"
      - "./users:/app/users"
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
    depends_on:
      - db
    ports:
      - 5005:5005
      - 3000:3000
    environment:
      - "DATABASE_URL=jdbc:mysql://db:3306/users"
      - "DATABASE_PORT=3306"
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD=password"
      - "HTTP_INTERFACE=0.0.0.0"
      - "HTTP_PORT=3000"
      - "KAFKA_HOST=kafka"
  groups:
    build:
      context: ./groups
    command: ["sbt","run"]
    volumes:
      - "./commons:/app/commons"
      - "./groups:/app/groups"
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
    environment:
      - "DATABASE_URL=jdbc:mysql://db:3306/groups"
      - "DATABASE_PORT=3306"
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD=password"
      - "HTTP_INTERFACE=0.0.0.0"
      - "HTTP_PORT=6000"
      - "KAFKA_HOST=kafka"
      - "HOST_USER=http://users:3000"
    ports:
      - 6000:6000
    depends_on:
      - db
      - users
      - zookeeper
      - kafka
  notifications:
    build:
      context: ./notifications
    command: ["sbt","run"]
    volumes:
      - "./commons:/app/commons"
      - "./notifications:/app/notifications"
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
    environment:
      - "KAFKA_HOST=kafka"
      - "DATABASE_URL=jdbc:mysql://db:3306/groups"
      - "HTTP_INTERFACE=0.0.0.0"
      - "HTTP_PORT=7000"
      - "HOST_USER=http://users:3000"
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 7000:7000
  zookeeper:
    build:
      context: docker/zookeeper
    ports:
      - 2181:2181
  kafka:
    hostname: kafka
    build:
      context: docker/kafka
    ports:
      - 9092:9092
      - 9091:9091
    depends_on:
      - zookeeper