version: "2"
services:
  user-db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./.db_vol:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=api
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=user
    expose:
      - 3306
  user:
    build:
      context: ./user
    command: ["sbt","run"]
    volumes:
      - ".:/app"
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
    depends_on:
      - user-db
    ports:
      - 5005:5005
      - 3000:3000
    environment:
      - "DATABASE_URL=jdbc:mysql://user-db:3306/user"
      - "DATABASE_PORT=3306"
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD=password"
      - "HTTP_INTERFACE=0.0.0.0"
      - "HTTP_PORT=3000"
  zookeeper:
    build:
      context: docker/zookeeper
    ports:
      - 2181:2181
  kafka:
    build:
      context: docker/kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper