version: "2"
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./db_vol:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=api
      - MYSQL_ROOT_PASSWORD=password