version: "2"
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./.docker/db_vol:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=api
      - MYSQL_ROOT_PASSWORD=password
    expose:
      - 3306
  it-tests:
    build:
      context: .
    command: ["sbt","it:test"]
    volumes:
      - ".:/app/user"
      - "../commons:/app/commons"
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
    depends_on:
      - db